---
title: "Examen distribuciones de probabilidad 2 - Respuestas del profesor"
author: "Moises"
date: "1/4/2020"
output: html_document
---

En una universidad, se sabe que el 25% de los alumnos realizan algún tipo de deporte. Se ha obtenido una muestra de 30 alumnos.

a) Si llamamos X a la variable aleatoria que cuenta el número de alumnos que realizan algún tipo de deporte, ¿qué tipo de distribución sigue X?

b) ¿Qué esperanza tiene X?

c) ¿Y varianza?

d) Calcula con R (o Python) la probabilidad de que más de 25 alumnos practiquen algún deporte.

e) Calcula con R (o Python) la probabilidad de que exactamente 15 alumnos practiquen algún deporte.

f) Calcula con R (o Python) la probabilidad de que de 10 alumnos o menos practiquen algún deporte.

a) Se trata de una B(30,0.25)

b) E(X) = 30*0.25

c) Var(X) = 30*0.25*0.75

d) 1-pbinom(25,size = 30, prob = 0.25)

e) dbinom(15,size = 30, prob = 0.25)

f) pbinom(10,size = 30, prob = 0.25)

El número medio de accidentes de coche en la ciudad de Mahón en 2 meses es de 2 accidentes.

a) ¿Qué distribución sigue la v.a. que cuenta el número de accidentes en 2 meses?

b) Calcula la esperanza

c) Calcula con R (o Python) la probabilidad de que no ocurra ningún accidente en 2 meses.

a) Po(2)

b) lambda = 2

c) dpois(0,2)

El 40% de un pueblo a las afueras de la ciudad de Pensilvania ve un concurso que dan por la tele. El concurso llama por teléfono a 15 personas del pueblo elegidas al azar. ¿De qué distribución se trata?

B(15,0.4)

En un bol muy grande tenemos, en total, 70 fresas, de entre las cuales 10 están podridas. Tomando un puñado de 20 fresas al azar y sin reemplazar ninguna de ellas, ¿qué distribución sigue la v.a. que cuenta el número de fresas podridas?

Da también la esperanza y la varianza de esta variable aleatoria.

X~H(10,60,20)

E(X) = 10*20/(70)

Var(X) = 10*20*60/(70)^2*((70-20)/(70-1))

Un test de matemáticas consta de 200 preguntas de verdadero o falso. Para una persona que respondiese al azar, ¿qué distribución seguiría la v.a. que cuenta el número de preguntas acertadas?

Da también la esperanza y la varianza de esta variable aleatoria.

X~B(200,0.5)

E(X) = 200*0.5

Var(X) = 200*0.5^2

Un test de matemáticas consta de 200 preguntas. Cada pregunta consta de 4 posibles respuestas con solo una correcta. Para una persona que respondiese al azar, ¿qué distribución seguiría la v.a. que cuenta el número de preguntas acertadas?

Da también la esperanza y la varianza de esta variable aleatoria.

X~B(200,0.25)

E(X) = 200*0.25

Var(X) = 200*0.25*0.75

Un test de matemáticas consta de 200 preguntas de verdadero o falso. Para una persona que respondiese al azar y por orden, ¿qué distribución seguiría la v.a. que cuenta el número de preguntas respondidas hasta el primer acierto?

Da también la esperanza y la varianza de esta variable aleatoria.

X~Ge(0.5)

E(X) = 1/0.5 ya que empieza en 1

Var(X) = 1/0.5

Para evitar ser arrestado al pasar el control de seguridad, un viajero ha colocado 7 pastillas de droga en una botella que contiene 14 píldoras de vitaminas, las cuales son muy similares a las otras. Si el policía de turno selecciona 4 pastillas aleatoriamente para analizarlas, ¿qué distribución sigue la v.a. que cuenta el número de pastillas de droga?

H(7,14,4)

Un servicio dedicado a la reparación de aires acondicionados recibe de media 27 llamadas diarias. ¿Qué distribución sigue la v.a. que cuenta el número de llamadas diarias?

Po(27)

Se lanza 53 veces un dado. ¿Qué distribución sigue la v.a. que cuenta cuántas veces ha salido un número impar? ¿Y la v.a. que cuenta el número de veces que ha salido un número par? ¿Y la v.a. que cuenta las veces que hemos obtenido exactamente el número "5"?

X~B(53,0.5) (caso impar)

Y~B(53,0.5) (caso par)

Z~B(53,1/6) (caso sacar "5")

El precio medio del litro de gasolina durante el próximo año se estima que puede oscilar entre 1.09€ y 2.53€. ¿De qué distribución de probabilidad se trata?

Da la esperanza

X~U([1.09,2.53])

E(X) = (1.09+2.53)/2

En una tienda del centro comercial, el tiempo medio de cola para poder pagar en caja es de 7 minutos. ¿De qué distribución de probabilidad se trata?

Da la esperanza y varianza

X~Exp(7)

E(x) = 1/7

Var(X) = 1/49