---
title: "R y Python"
author: "Moises"
date: "9/2/2020"
output:
  html_document:
    df_print: paged
---
## Reticulate
```{r}
library(reticulate)
use_python("/Users/moise/Anaconda3/python.exe",required = TRUE)
#Esta libreria permite utilizar todas las funciones de Python en R
#Se recomienda luego de cargar reticulate usar use_python para indicarle donde esta el python que instalaste que es el que tiene todos los paquetes de anaconda
#Si deseas instalarle un paquete extra, utiliza la funcion py_install("Nombre del paquete")
#Solo se cargara esta libreria en este documento porque la cargue en este chunk
#Esta libreria permite utilizar todas las funciones de Python en R
os <- import("os") 
#Estoy guardando esta libreria de python en esta variable 
#y se puede invocar cualquiera de sus funciones utilizando la variable que cree "os"

os$listdir(".") 
#La funcion listdir enlista todos los ficheros que estan en el directorio donde ejecute esta funcion

```

Muestra la raiz cuadrada de 4 en python
```{r}
math <- import("math") 
math$sqrt(4) 
#Aqui importe el package de math en python y llame a la funcion sqrt
```

Muestra mi codigo python del fichero PruebaReticulate2.py
```{r}
source_python("PruebaReticulate2.py")
suma(3,4)
#Es como un include de php basicamente
```

Para convertir de Python a r
```{r}
np <- import("numpy", convert = FALSE)
x <- np$array(c(1:4)) 
sum <- x$cumsum()
print(sum) #Aqui muestra una lista pero que todavia esta en Python

py_to_r(sum) #Ahora si ya lo muestra en el formato de r
```


Si deseas consultar que hace alguna funcion o libreria de python desde r
```{r}
py_help(os$chdir) #Pero esto solo se muestra en consola, recuerda siempre cargar reticulate y la libreria que estas llamando (En este caso es "os")
```


## Arrays de Python en r
```{r}
a <- np_array(c(1:10), dtype="int")
a
```


## Tambien se puede cargar de r a PYTHON
```{r}
datos <- iris
head(datos) 
datos_py <- r_to_py(datos)
```

```{python}
import numpy as np
import pandas as pd

r.datos_py.head() #Aqui puedes acceder a cualquier clase o metodo de r que haya expuesto a python utilizando la funcion r_to_py

```

## Ejmplo utilizando numpy
```{python}
a= np.array([1,2,4])
print("1D ARRAY:")
print(a)

b= np.array([(1,2,4),(1,2,4),(1,2,4)])
print("2D ARRAY:")
print(b)

```


## Demostrando que numpy ocupa menos memoria
```{python}
import sys

S= range(1000)
print("Resultado lista de python:")
print(sys.getsizeof(5)*len(S))
print()

D= np.arange(1000)
print("Resultado lista de Numpy:")
print(D.size*D.itemsize)


```

