---
title: "Factores"
author: "Moises"
date: "11/2/2020"
output: html_document
---

### Factor: 
Es como un vector, pero con una estructura interna más rica que permite usarlo para clasificar observaciones
```{r}
nombres = c("Juan","Maria","Moises","Pedro","Juan","Vane","Lisa")
nombres_f = factor(nombres)
nombres_f

generos = c("M","H","M","M","H","M","M","H")
generos_f = factor(generos)
generos_f

#Para agregar otro nivel
generos_f = factor(generos, levels = c("M","H","B"), labels = c("Mujer","Hombre","Bisexual"))
generos_f

#Si se desea mostrar los niveles declarados
levels(generos_f)

#Si se desea cambiar los valores del factor solo cambiando los niveles
levels(generos_f) = c("Femenino","Masculino","Hibrido")
generos_f
```

### Categorizacion de vectores: 
Los factores son muy utiles para categorizar
```{r}
notas = c(1,2,3,4,4,5,4,5,1,3,2,5,5,2)
notas_factor = factor(notas)
notas_factor
#Aqui el factor a categorizado el vector en sus 5 valores 
#Y podemos etiquetar cada uno de esos valores
levels(notas_factor) = c("Pesimo!","Malo","Bueno","Muy bien","Excelente!")
notas_factor

#Tambien dichos valores se pueden agrupar en menos grupos segun su valor
levels(notas_factor) = c("desaprobado","desaprobado","aprobado","aprobado","aprobado")
notas_factor
```


### Factor ordenado 
Es un factor donde los niveles siguen un orden
ordered(vector,levels=...): función que define un factor ordenado y tiene los mismos parámetros que factor
```{r}
#Siguiendo el mismo ejemplo si deseamos ordenar las notas solo aplicarle un ordered
notas = c(1,2,3,4,4,5,4,5,1,3,2,5,5,2)
notas_factor_ordered = ordered(notas,labels = c("Pesimo!","Malo","Bueno","Muy bien","Excelente!"))
notas_factor_ordered
```
