-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Servidor: localhost:3306
-- Tiempo de generación: 25-02-2020 a las 18:35:39
-- Versión del servidor: 10.3.22-MariaDB
-- Versión de PHP: 7.3.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `asenfi_base1`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `asambleas`
--

CREATE TABLE `asambleas` (
  `Codigo` int(11) NOT NULL,
  `Codigo_edificio` int(11) NOT NULL,
  `nombre_edificio` varchar(300) COLLATE utf8_unicode_ci NOT NULL,
  `silla` int(11) NOT NULL,
  `tipo` varchar(300) COLLATE utf8_unicode_ci NOT NULL,
  `dia` int(11) NOT NULL,
  `mes` varchar(300) COLLATE utf8_unicode_ci NOT NULL,
  `ano` varchar(300) COLLATE utf8_unicode_ci NOT NULL,
  `dia_digitada` int(11) NOT NULL,
  `mes_digitada` int(11) NOT NULL,
  `ano_digitada` int(11) NOT NULL,
  `hora` varchar(300) COLLATE utf8_unicode_ci NOT NULL,
  `lugar_encuentro` varchar(400) COLLATE utf8_unicode_ci NOT NULL,
  `situaciones` text COLLATE utf8_unicode_ci NOT NULL,
  `nota` text COLLATE utf8_unicode_ci NOT NULL,
  `imagen_minuta` text COLLATE utf8_unicode_ci NOT NULL,
  `imagen_asamblea` text COLLATE utf8_unicode_ci NOT NULL,
  `imagen_acta_presencial` text COLLATE utf8_unicode_ci NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Volcado de datos para la tabla `asambleas`
--

INSERT INTO `asambleas` (`Codigo`, `Codigo_edificio`, `nombre_edificio`, `silla`, `tipo`, `dia`, `mes`, `ano`, `dia_digitada`, `mes_digitada`, `ano_digitada`, `hora`, `lugar_encuentro`, `situaciones`, `nota`, `imagen_minuta`, `imagen_asamblea`, `imagen_acta_presencial`) VALUES
(94, 20, 'Torre Carmil V', 2, 'ordinaria', 28, 'Mayo', '2018', 11, 5, 2018, '7:00 PM', 'Area social', '1. Resumen de Gestion Financiera<br>;2. Temas libres<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(95, 74, 'Torre Natali', 1, 'extraordinaria', 30, 'Mayo', '2018', 14, 5, 2018, '7:00 PM', 'de  paqueo', '1. Prohibición de cambios a la estructura de la fachada y área comunes sin la aprobación de la asamblea.<br>;2. Reorganización de los parqueos asignados a cada apartamento, de acuerdo al plano aprobado por el Ayuntamiento del DN, consignado en la constitución Condominio de la Torre Natali depositados en el Registro de Títulos del Distrito Nacional.<br>;3. Conclusión con los trabajos de plafón en los techos de los estacionamientos por parte de la Constructora, de acuerdo a requerimientos hechos en asambleas anteriores.<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(92, 72, 'edificio de prueba 3', 1, 'extraordinaria', 6, 'Marzo', '2018', 7, 5, 2018, '4:00 PM', 'dsdsdsd', '1. sss<br>;2. dsdsfffsf<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(93, 89, 'Torre Galco VIII', 1, 'ordinaria', 7, 'Junio', '2018', 10, 5, 2018, '7:00 PM', 'Parqueo', '1. Estados Financieros.<br>;2. Elección de directiva. <br>;3. Temas Libres<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(90, 100, 'Residencial Janice', 2, 'ordinaria', 17, 'Mayo', '2018', 3, 5, 2018, '7:00 PM', 'Area comun. ', '1. Estados Financieros<br>;2. Situacion Bomba de agua y cambio de vigilancia<br>;3. Temas Libres<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(91, 52, 'Condominio Summa I', 2, 'ordinaria', 22, 'Mayo', '2018', 7, 5, 2018, '7:00 PM', 'Area comun. ', '1. Estados Financieros<br>;2. Presupuesto para la  Torre<br>;3. Cambio de directiva <br>;4. Temas Libres.<br>;;;;;;;;;;;;;;;;', '', '', '', ''),
(88, 48, 'Residencial Rigo I', 1, 'ordinaria', 26, 'Mayo', '2018', 27, 4, 2018, '4:00 PM', 'Parqueo', '1. Resumen Financiero<br>;2. Metas por realizar<br>;3. Confirmación de la directiva<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(89, 106, 'Torre Regatta IV', 0, 'extraordinaria', 23, 'Mayo', '2018', 2, 5, 2018, '7:00 PM', 'salón 7mo piso', '1. Informe financiero<br>;2. Metas pendientes de realizar <br>;3. Temas libres<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(7, 17, 'Residencial MJ4', 0, 'extraordinaria', 19, 'Abril', '2017', 5, 4, 2017, '7:00 PM', 'parqueo del residencial', '1. Presentacion informe financiero<br>;2. Metas pendientes<br>;3. Temas libres<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(8, 17, 'Residencial MJ4', 0, 'extraordinaria', 19, 'Abril', '2017', 5, 4, 2017, '7:00 PM', 'parqueo del residencial', '1. Presentacion informe financiero<br>;2. Metas pendientes<br>;3. Temas libres<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(9, 71, 'Edificio_prueba2', 1, 'extraordinaria', 6, 'Noviembre', '2018', 5, 4, 2017, '2:00 AM', 'parqueo de la torre', '1. PresentaciÃ³n e informe financiero de la compaÃ±Ã­a administradora.<br>;2. RevisiÃ³n de los ingresos y gastos de la torre.<br>;3. SituaciÃ³n deuda con la constructora PeÃ±a Abreu & Asociados.<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(10, 20, 'Torre Carmil V', 2, 'ordinaria', 17, 'Mayo', '2017', 21, 4, 2017, '7:00 PM', 'social de la torre', '1. Presentacion informe financiero<br>;2. Uso de la cuota extra<br>;3. Eleccion de la nueva directiva<br>;4. Eleccion de la nueva directiva<br>;5. Temas libres<br>;;;;;;;;;;;;;;;', '', '', '', ''),
(11, 18, 'Residencial Anabella', 2, 'extraordinaria', 16, 'Mayo', '2017', 10, 5, 2017, '7:00 PM', 'de parqueo del residencial', '1. Informe Financiero<br>;2. Temas libres<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(12, 80, 'Torre Nabis Naco', 2, 'extraordinaria', 6, 'Junio', '2017', 22, 5, 2017, '7:00 PM', 'social de la torre', '1. Informe Financiero<br>;2. Metas pendientes<br>;3. Monto del mantenimiento y revisiÃ³n de cuota apartamentos penthouse<br>;4. Ãrea de comida y descanso del personal.<br>;5. Rampa parqueos<br>;6. Temas libres<br>;;;;;;;;;;;;;;', '', '', '', ''),
(13, 86, 'Gardenias I', 1, 'extraordinaria', 22, 'Junio', '2017', 16, 6, 2017, '7:00 PM', 'del parqueo del residencial', '1. Cambio fachada de las areas comunes (Favor remitirse a las pags. 35 - 49 del reglamento)<br>;2. Situacion del agua en el residencial<br>;3. Eleccion del diseÃ±o para construir en la azotea <br>;4. Temas libres<br>;;;;;;;;;;;;;;;;', '', '', '', ''),
(14, 86, 'Gardenias I', 1, 'extraordinaria', 22, 'Junio', '2017', 19, 6, 2017, '8:00 PM', 'de parqueo del residencial', '1. Solicitud de cambio de estructura divisora entre patio privado y Ã¡rea comÃºn, solicitado por el Sr. Juan Ferreira y el Sr. Lohendy Morillo<br>;2. ReorganizaciÃ³n de la Directiva del condominio<br>;3. Temas Libres<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(15, 89, 'Torre Galco VIII', 1, 'extraordinaria', 20, 'Julio', '2017', 5, 7, 2017, '7:00 PM', 'social de la torre', '1. Estado financiero de la torre<br>;2. Revision cuota de mantenimiento<br>;3. Temas libres<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(16, 51, 'Residencial Soler III', 1, 'extraordinaria', 10, 'Agosto', '2017', 7, 8, 2017, '7:00 PM', ' de paqueo del residencial.', '1. SituaciÃ³n financiera<br>;2. Temas libres<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(17, 71, 'Edificio_prueba2', 1, 'extraordinaria', 8, 'Abril', '2015', 17, 8, 2017, '2:00 AM', 'parqueo de la torre', '1. PresentaciÃ³n e informe financiero de la compaÃ±Ã­a administradora.<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(18, 71, 'Edificio_prueba2', 1, 'extraordinaria', 3, 'Mayo', '2018', 17, 8, 2017, '3:00 AM', 'parqueo de la torre', '1. PresentaciÃ³n e informe financiero de la compaÃ±Ã­a administradora.<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(19, 71, 'Edificio_prueba2', 1, 'extraordinaria', 5, 'Mayo', '2017', 17, 8, 2017, '2:00 AM', 'parqueo de la torre', '1. PresentaciÃ³n e informe financiero de la compaÃ±Ã­a administradora.<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(20, 71, 'Edificio_prueba2', 1, 'extraordinaria', 4, 'Febrero', '2015', 24, 8, 2017, '2:00 AM', 'parqueo de la torre', '1. prueba<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(21, 71, 'Edificio_prueba2', 1, 'extraordinaria', 4, 'Enero', '2016', 24, 8, 2017, '1:00 AM', 'parqueo de la torre', '1. prueba<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(22, 71, 'Edificio_prueba2', 1, 'ordinaria', 17, 'Marzo', '2030', 31, 8, 2017, '2:00 AM', ' de paqueo del residencial.', '1. SituaciÃ³n financiera<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(23, 95, 'Residencial Filadelfia III', 2, 'extraordinaria', 3, 'Octubre', '2017', 15, 9, 2017, '7:00 PM', 'En el Parqueo', '1. Temas Financieros del Residencial<br>;2. Pintura del Residencial<br>;3. Tema Abierto.<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(24, 19, 'Torre NE', 2, 'extraordinaria', 28, 'Octubre', '2017', 12, 10, 2017, '3:00 PM', 'del parqueo', '1. SituaciÃ³n Financiera Condominio  <br>;2. Incremento cuota mensual<br>;3. Necesidades de InversiÃ³n/Mantenimiento<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(25, 105, 'Torre Neapolis II', 1, 'ordinaria', 30, 'Octubre', '2017', 12, 10, 2017, '7:00 PM', 'salÃ³n del nivel 1', '1. PresentaciÃ³n de la nueva administraciÃ³n<br>;2. Estado financiero<br>;3. Calculo del mantenimiento real de condominio. (presupuesto)<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(26, 99, 'Residencial Palmera Oriental II', 2, 'extraordinaria', 11, 'Noviembre', '2017', 19, 10, 2017, '4:00 PM', 'Gazebo', '1. Informe financiero del residencial<br>;2. Seguridad<br>;3. Funciones de la AdministraciÃ³n y directiva<br>;4. Metas pendiente por realizar<br>;5. Autoridad de la administraciÃ³n<br>;6. Objetivo de la administraciÃ³n<br>;7. Temas libre<br>;;;;;;;;;;;;;', '', '', '', ''),
(27, 71, 'Edificio_prueba2', 1, 'extraordinaria', 2, 'Marzo', '2017', 23, 10, 2017, '4:00 AM', 'PresentaciÃ³n e informe financiero de la compaÃ±Ã­a administradora.', '1. PresentaciÃ³n e informe financiero de la compaÃ±Ã­a administradora.<br>;2. PresentaciÃ³n e informe financiero de la compaÃ±Ã­a administradora.<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(28, 71, 'Edificio_prueba2', 1, 'extraordinaria', 4, 'Abril', '2017', 23, 10, 2017, '3:00 AM', 'parqueo de la torre', '1. PresentaciÃ³n e informe financiero de la compaÃ±Ã­a administradora.<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(29, 99, 'Residencial Palmera Oriental II', 2, 'extraordinaria', 18, 'Noviembre', '2017', 27, 10, 2017, '4:00 PM', 'Gazebo', '1. Informe financiero del residencial<br>;2. Seguridad<br>;3. Funciones de la AdministraciÃ³n y directiva<br>;4. Metas pendiente por realizar<br>;5. Autoridad de la administraciÃ³n<br>;6. Objetivo de la administraciÃ³n<br>;7. Temas libre<br>;;;;;;;;;;;;;', '', '', '', ''),
(30, 105, 'Torre Neapolis II', 2, 'ordinaria', 30, 'Octubre', '2017', 27, 10, 2017, '7:00 PM', 'salÃ³n del nivel 1', '1. PresentaciÃ³n de la Comitiva.<br>;2. Estatus de la Torre y la Constructora.<br>;3. Cuotas de Mantenimiento regular y extraordinaria<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(31, 105, 'Torre Neapolis II', 2, 'ordinaria', 30, 'Octubre', '2017', 27, 10, 2017, '7:00 PM', 'salon del nivel 1', '1. PresentaciÃ³n de la Comitiva.<br>;2. Estatus de la Torre y la Constructora.<br>;3. Cuotas de Mantenimiento regular y extraordinaria<br>;4. ...<br>;;;;;;;;;;;;;;;;', '', '', '', ''),
(32, 105, 'Torre Neapolis II', 2, 'ordinaria', 30, 'Octubre', '2017', 27, 10, 2017, '7:00 PM', 'salon del nivel 1', '1. PresentaciÃ³n de la Comitiva.<br>;2. Estatus de la Torre y la Constructora.<br>;3. Cuotas de Mantenimiento regular y extraordinaria<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(33, 82, 'Residencial LP-8', 2, 'extraordinaria', 19, 'Noviembre', '2017', 2, 11, 2017, '4:00 PM', 'de gazebo', '1. Ãšnico tema: El uso de la azotea<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(34, 82, 'Residencial LP-8', 2, 'extraordinaria', 19, 'Noviembre', '2017', 2, 11, 2017, '4:00 PM', 'de gazebo', '1. Ãšnico tema: El uso de la azotea<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(35, 99, 'Residencial Palmera Oriental II', 2, 'extraordinaria', 2, 'Diciembre', '2017', 3, 11, 2017, '4:00 PM', 'Gazebo', '1. Informe financiero del residencial<br>;2. Seguridad<br>;3. Funciones de la AdministraciÃ³n y directiva<br>;4. Metas pendiente por realizar<br>;5. Autoridad de la administraciÃ³n<br>;6. Objetivo de la administraciÃ³n<br>;7. Temas libre<br>;;;;;;;;;;;;;', '', '', '', ''),
(36, 69, 'Torre P-A-37', 1, 'extraordinaria', 1, 'Diciembre', '2017', 16, 11, 2017, '7:00 PM', 'Parqueo Torre P-A-37', '1. Estado financiero actual<br>;2. ElecciÃ³n de miembros complementarios directiva<br>;3. SituaciÃ³n apartamento B-2-8<br>;4. Presupuesto de mejoras para el condominio<br>;;;;;;;;;;;;;;;;', '', '', '', ''),
(37, 71, 'Edificio_prueba2', 1, 'extraordinaria', 12, 'Octubre', '2023', 19, 11, 2017, '10:00 AM', 'parqueo de la torre', '1. PresentaciÃ³n e informe financiero de la compaÃ±Ã­a administradora.<br>;2. kkkkkkkkkk<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(38, 71, 'Edificio_prueba2', 1, 'extraordinaria', 15, 'Septiembre', '2028', 19, 11, 2017, '3:00 AM', 'parqueo de la torre', '1. PresentaciÃ³n e informe financiero de la compaÃ±Ã­a administradora.<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(39, 71, 'Edificio_prueba2', 1, 'extraordinaria', 1, 'Enero', '2015', 19, 11, 2017, '2:00 AM', 'parqueo de la torre', '1. PresentaciÃ³n e informe financiero de la compaÃ±Ã­a administradora.<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(40, 71, 'Edificio_prueba2', 1, 'extraordinaria', 11, 'Octubre', '2021', 19, 11, 2017, '2:00 AM', 'parqueo de la torre', '1. Contratar empresa de seguridad armada<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(41, 71, 'Edificio_prueba2', 1, 'extraordinaria', 3, 'Marzo', '2016', 19, 11, 2017, '4:00 AM', 'parqueo de la torre', '1. prueba<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(42, 71, 'Edificio_prueba2', 1, 'extraordinaria', 13, 'Junio', '2029', 19, 11, 2017, '3:00 AM', 'parqueo de la torre', '1. PresentaciÃ³n e informe financiero de la compaÃ±Ã­a administradora.<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(43, 71, 'Edificio_prueba2', 1, 'ordinaria', 3, 'Febrero', '2016', 19, 11, 2017, '4:00 AM', 'PresentaciÃ³n e informe financiero de la compaÃ±Ã­a administradora.', '1. PresentaciÃ³n e informe financiero de la compaÃ±Ã­a administradora.<br>;2. - Hablar sobre la aprobacion de la cuota para las regalias navideÃ±as <br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(44, 105, 'Torre Neapolis II', 2, 'extraordinaria', 7, 'Diciembre', '2017', 20, 11, 2017, '7:00 PM', 'salÃ³n del nivel 1', '1. Status de Pagos Ordinarios y Extraordinarios.<br>;2. RegularizaciÃ³n del Servicio de EnergÃ­a ElÃ©ctrica<br>;3. RevisiÃ³n y acuerdo Reglas de Condominio.<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(45, 113, 'Residencial Garden City', 1, 'extraordinaria', 3, 'Diciembre', '2017', 22, 11, 2017, '4:00 PM', 'En parqueo del condominio', '1. Presupuesto y cuota de mantenimiento<br>;2. Instalacion gas comun<br>;3. Temas libres<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(46, 71, 'Edificio_prueba2', 0, 'extraordinaria', 5, 'Abril', '2019', 1, 12, 2017, '5:00 AM', 'parqueo de la torre', '1. Hablar sobre la aprobacion de la cuota para las regalias navideÃ±as <br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(47, 79, 'Torre Mineri IV', 1, 'ordinaria', 10, 'Enero', '2018', 7, 12, 2017, '8:00 PM', 'parqueo', '1. ElecciÃ³n de nueva directiva<br>;2. Temas libres<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(61, 96, 'Residencial Don Juan II', 0, 'ordinaria', 6, 'Febrero', '2018', 17, 1, 2018, '7:00 PM', 'Entrada del Primer Piso', '1. Emision del RNC<br>;2. Pintura del Edificio<br>;3. Instalacion control de Acceso<br>;4. Tema Libre<br>;;;;;;;;;;;;;;;;', '', '', '', ''),
(49, 86, 'Gardenias I', 1, 'extraordinaria', 19, 'Diciembre', '2017', 14, 12, 2017, '8:00 PM', ' de Parqueo. ', '1. ElecciÃ³n de nueva directiva.<br>;2. AprobaciÃ³n de funciones de la Directiva y Funciones de la AdministraciÃ³n<br>;3. PrivatizaciÃ³n de Ã¡reas Comunes. <br>;4. Temas Libres.<br>;;;;;;;;;;;;;;;;', '', '', '', ''),
(50, 111, 'Torre niza III', 0, 'ordinaria', 12, 'Enero', '2018', 14, 12, 2017, '7:00 PM', 'del Lobby.', '1. Estado Financiero<br>;2. Temas libres<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(59, 82, 'Residencial LP-8', 2, 'ordinaria', 14, 'Enero', '2018', 5, 1, 2018, '5:00 PM', 'Gazebo', '1. Informe financiero de Asenfi, de la GestiÃ³n Marzo-Diciembre<br>;2. solucion al tema de la CASSD,<br>;3. Organizacion de las elecciones<br>;4. Presupuesto del aÃ±o 2018<br>;;;;;;;;;;;;;;;;', '', '', '', ''),
(52, 80, 'Torre Nabis Naco', 0, 'extraordinaria', 27, 'Diciembre', '2017', 20, 12, 2017, '7:00 PM', 'Area Social.', '1. ElecciÃ³n de nueva directiva<br>;2. Temas pendientes de trabajos a realizar<br>;3. Tema constructora vecina y horarios<br>;4. Presupuesto del condominio.<br>;;;;;;;;;;;;;;;;', '', '', '', ''),
(53, 97, 'Torre Lozada', 1, 'ordinaria', 16, 'Enero', '2018', 21, 12, 2017, '7:00 AM', 'Parqueo', '1. Estados Financieros<br>;2. Trabajos pendiente por realizar<br>;3. Seguridad perimentral<br>;4. Uniforme de los empleados<br>;5. Funciones de la AdministraciÃ³n.<br>;;;;;;;;;;;;;;;', '', '', '', ''),
(54, 105, 'Torre Neapolis II', 2, 'extraordinaria', 25, 'Enero', '2017', 29, 12, 2017, '7:00 PM', 'salon del nivel 1', '1. El estatus del pago a la Constructora.<br>;2. Cuentas por cobrar: definir aptos vacÃ­os y cobros.<br>;3. Metas pendientes como InstalaciÃ³n independiente de gas, espejo de ascensor, posible sistema de cÃ¡maras...<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(55, 105, 'Torre Neapolis II', 2, 'extraordinaria', 25, 'Enero', '2018', 29, 12, 2017, '7:00 PM', 'salon del nivel 1', '1. El estatus del pago a la Constructora.<br>;2. Cuentas por cobrar: definir aptos vacÃ­os y cobros.<br>;3. Metas pendientes como InstalaciÃ³n independiente de gas, espejo de ascensor, posible sistema de cÃ¡maras...<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(56, 74, 'Torre Natali', 2, 'extraordinaria', 7, 'Febrero', '2018', 2, 1, 2018, '7:00 PM', 'del parqueo', '1. Resumen financiero (caso del exceso en deudas en las cuentas por cobrar del condominio)<br>;2. Metas pendientes<br>;3. Tema libre para que los propietarios expongan el tema que consideren<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(57, 96, 'Residencial Don Juan II', 1, 'ordinaria', 17, 'Enero', '2018', 3, 1, 2018, '7:00 PM', 'Entrada del Primer Piso', '1. Emision del RNC<br>;2. Pintura del Edificio<br>;3. Instalacion control de Acceso.<br>;4. Tema Libre<br>;;;;;;;;;;;;;;;;', '', '', '', ''),
(58, 46, 'Torre De Las Fuentes I', 2, 'extraordinaria', 18, 'Enero', '2018', 4, 1, 2018, '7:00 PM', 'social', '1.  Remozamiento de las Ã¡reas comunes (fachada, parqueo, pisos y techos)<br>;2. Seguridad en el condominio<br>;3. Tema libre para inquietudes de los condomines<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(60, 115, 'Terraza Al Jardin', 2, 'ordinaria', 24, 'Enero', '2018', 10, 1, 2018, '8:00 PM', 'de salÃ³n de eventos social', '1. Cambio de compaÃ±ia de vigilancia<br>;2. Aumento de sueldo a empleados y programa de incentivo<br>;3. Presupuesto del aÃ±o<br>;4. Sistema de multas<br>;5. Control de mudanzas, depÃ³sitos, y reservaciones<br>;6. Temas Libres<br>;;;;;;;;;;;;;;', '', '', '', ''),
(62, 111, 'Torre niza III', 1, 'ordinaria', 31, 'Enero', '2018', 23, 1, 2018, '7:00 PM', 'Area del Lobby', '1. Estados Financieros<br>;2. Mejoras para el Residencial<br>;3. Uso del Lobby<br>;4. Cambio de directiva.<br>;;;;;;;;;;;;;;;;', '', '', '', ''),
(63, 86, 'Gardenias I', 1, 'extraordinaria', 13, 'Febrero', '2018', 25, 1, 2018, '7:00 PM', 'Parqueo', '1. Cambio de directiva<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(64, 89, 'Torre Galco VIII', 1, 'extraordinaria', 13, 'Febrero', '2018', 25, 1, 2018, '7:00 PM', 'de parqueo. ', '1. Cambio de directiva<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(65, 80, 'Torre Nabis Naco', 0, 'extraordinaria', 2, 'Febrero', '2018', 30, 1, 2018, '7:00 PM', ' Social.', '1. Cambio de directiva<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(66, 80, 'Torre Nabis Naco', 0, 'extraordinaria', 8, 'Febrero', '2018', 6, 2, 2018, '7:00 PM', 'comun', '1. Cambio de directiva<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(67, 80, 'Torre Nabis Naco', 0, 'extraordinaria', 20, 'Febrero', '2018', 8, 2, 2018, '7:00 PM', 'comun', '1. Cambio de directiva<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(68, 89, 'Torre Galco VIII', 0, 'extraordinaria', 1, 'Marzo', '2018', 13, 2, 2018, '7:00 PM', 'Parqueo', '1. Cambio de directiva<br>;2. Aumento de cuota.<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(69, 82, 'Residencial LP-8', 2, 'ordinaria', 18, 'Febrero', '2018', 14, 2, 2018, '5:00 PM', 'Gazebo', '1. Elecciones <br>;2. Presupuesto<br>;3. Ratificación o cambio de la Administración<br>;;;;;;;;;;;;;;;;;', 'IMPORTANTE: FAVOR LLEVAR SU CÉDULA ', '', '', ''),
(70, 113, 'Residencial Garden City', 1, 'extraordinaria', 18, 'Febrero', '2018', 15, 2, 2018, '4:00 PM', 'Parqueo del condominio', '1. •	Reubicación oficina administración.<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(71, 117, 'Residencial G-24', 2, 'ordinaria', 21, 'Febrero', '2018', 21, 2, 2018, '7:00 PM', 'El parqueo', '1. Presentación de la Administración<br>;2. Presentación de la directiva<br>;3. Metas pendientes del condominio<br>;4. Analisis financiero<br>;;;;;;;;;;;;;;;;', '', '', '', ''),
(72, 97, 'Torre Lozada', 1, 'ordinaria', 9, 'Marzo', '2018', 23, 2, 2018, '7:00 PM', 'parqueo. ', '1. Estados Financieros<br>;2. Trabajos pendiente por realizar<br>;3. Seguridad perimentral<br>;4. Uniforme de los empleados<br>;5. Funciones de la Administracion<br>;6. Presupuesto de la Torre. <br>;;;;;;;;;;;;;;', '', '', '', ''),
(73, 107, 'Residencial Las Palmeras', 2, 'extraordinaria', 18, 'Marzo', '2018', 9, 3, 2018, '4:00 PM', 'Área de Gacebo Boulevard', '1. Informe general-financiero<br>;2. Temas libres<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(74, 97, 'Torre Lozada', 1, 'ordinaria', 16, 'Marzo', '2018', 9, 3, 2018, '7:00 PM', 'parqueo. ', '1. Estados Financieros<br>;2. Uniforme de los empleados<br>;3. Presupuesto de la Torre<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(75, 71, 'Edificio_prueba2', 1, 'extraordinaria', 3, 'Febrero', '2018', 13, 3, 2018, '3:00 AM', 'adsds', '1. Presentación e informe financiero de la compañía administradora.<br>;2. - Hablar sobre la aprobacion de la cuota para las regalias navideñas<br>;3. kkj<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(76, 71, 'Edificio_prueba2', 1, 'extraordinaria', 6, 'Marzo', '2017', 16, 3, 2018, '9:00 AM', 'adsds', '1. Presentación e informe financiero de la compañía administradora.<br>;2. kkkkkkkkkk<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(77, 82, 'Residencial LP-8', 2, 'extraordinaria', 25, 'Marzo', '2018', 17, 3, 2018, '5:00 PM', ' del gazebo', '1. Presupuesto<br>;2. Elección de la nueva Empresa Administradora<br>;;;;;;;;;;;;;;;;;;', '\r\n\r\n', '', '', ''),
(78, 118, 'Torre Teraluz II', 0, 'ordinaria', 22, 'Marzo', '2018', 20, 3, 2018, '7:00 PM', 'Area comun. ', '1. Presentación de la Administracion<br>;2. Presupuesto del Condominio,<br>;3. Propuesta de normas de convivencia para el condominio. <br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(79, 52, 'Condominio Summa I', 2, 'ordinaria', 18, 'Abril', '2018', 28, 3, 2018, '7:00 PM', 'Salon de Reuniones', '1. Estados Financieros<br>;2. Presupuesto para la  Torre<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(80, 51, 'Residencial Soler III', 1, 'extraordinaria', 19, 'Abril', '2018', 2, 4, 2018, '7:00 PM', 'de parqueo', '1. Informe financiero<br>;2. Metas pendientes de realizar <br>;3. Temas libres<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(81, 80, 'Torre Nabis Naco', 0, 'extraordinaria', 9, 'Abril', '2018', 4, 4, 2018, '7:00 PM', 'Área común.', '1. Ratificación directiva<br>;2. Revaluar propuesta del uso medidores de gas<br>;3. Temas Libre<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(82, 55, 'Torre Nicole II', 1, 'ordinaria', 12, 'Abril', '2018', 7, 4, 2018, '8:00 PM', 'Area comun', '1. Estados Financieros<br>;2. Aumento de cuota.<br>;3. Rigurosidad de corte de los servicios<br>;4. Cambio de directiva<br>;5. Tema Libre<br>;;;;;;;;;;;;;;;', '', '', '', ''),
(83, 71, 'Edificio_prueba2', 1, 'extraordinaria', 11, 'Noviembre', '2028', 8, 4, 2018, '8:00 AM', 'sss', '1. sss<br>;;;;;;;;;;;;;;;;;;;', 'sdsds', '', '', ''),
(84, 106, 'Torre Regatta IV', 0, 'extraordinaria', 3, 'Mayo', '2018', 11, 4, 2018, '7:00 PM', 'Salón multiuso 7mo piso', '1. Informe financiero<br>;2. Metas pendientes de realizar <br>;3. Temas libres<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(85, 52, 'Condominio Summa I', 2, 'ordinaria', 7, 'Mayo', '2018', 18, 4, 2018, '7:00 PM', 'Salon de Reuniones', '1. Estados Financieros<br>;2. Presupuesto para la Torre<br>;3. Cambio de directiva<br>;4. Temas Libres.<br>;;;;;;;;;;;;;;;;', '', '', '', ''),
(86, 71, 'Edificio_prueba2', 1, 'extraordinaria', 6, 'Abril', '2018', 18, 4, 2018, '4:00 AM', 'wewe', '1. sss<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(87, 100, 'Residencial Janice', 2, 'ordinaria', 3, 'Mayo', '2018', 19, 4, 2018, '7:00 PM', 'Area comun. ', '1. Estados Financieros<br>;2. Seguridad Armada y situación actual Bomba de agua.<br>;3. Temas Libres<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(96, 113, 'Residencial Garden City', 1, 'extraordinaria', 20, 'Mayo', '2018', 14, 5, 2018, '4:00 PM', 'En parqueo del condominio', '1. Construccion de la oficina administrativa<br>;2. Status de cuentas por cobrar<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(97, 100, 'Residencial Janice', 2, 'ordinaria', 4, 'Junio', '2018', 16, 5, 2018, '7:00 PM', 'Area comun. ', '1. Estados Financieros<br>;2. Situacion Bomba de agua y cambio de vigilancia<br>;3. Temas Libres<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(98, 124, 'Regatta Unique', 2, 'ordinaria', 7, 'Junio', '2018', 17, 5, 2018, '7:00 PM', 'Gazebo', '1. Presentación de la empresa de administración<br>;2. Presupuesto del año del condominio<br>;3.  Las metas del año<br>;4. sugerencias de la administracion <br>;5. Temas libres<br>;;;;;;;;;;;;;;;', '', '', '', ''),
(99, 48, 'Residencial Rigo I', 1, 'ordinaria', 11, 'Junio', '2018', 22, 5, 2018, '7:00 PM', 'Parqueo del residencial', '1. Resumen de Gestion Financiera<br>;2. Metas pendientes de realizar <br>;3. Confirmación de la directiva<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(100, 52, 'Condominio Summa I', 2, 'ordinaria', 30, 'Mayo', '2018', 24, 5, 2018, '7:00 PM', 'salon de la Torre', '1. Estados Financieros<br>;2. Presupuesto para la Torre<br>;3. Cambio de directiva <br>;4. Temas libres<br>;;;;;;;;;;;;;;;;', '', '', '', ''),
(101, 20, 'Torre Carmil V', 0, 'extraordinaria', 21, 'Junio', '2018', 28, 5, 2018, '7:00 PM', 'Area social', '1. Resumen de Gestion Financiera<br>;2. Temas libres<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(102, 81, 'Torre Nuevo Sol', 2, 'ordinaria', 14, 'Junio', '2018', 28, 5, 2018, '7:00 PM', 'Parqueo', '1. Informe financiero<br>;2. Temas Libres<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(103, 46, 'Torre De Las Fuentes I', 2, 'extraordinaria', 14, 'Junio', '2018', 30, 5, 2018, '7:00 PM', 'Area social', '1. Resumen de Gestion Financiera<br>;2. Metas pendientes de realizar <br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(104, 81, 'Torre Nuevo Sol', 1, 'extraordinaria', 21, 'Junio', '2018', 15, 6, 2018, '7:00 PM', 'Parqueo', '1. Informe financiero<br>;2. Temas Libres<br>;;;;;;;;;;;;;;;;;;', 'Llevar poder firmado en caso de representación de otro propietario', '', '', ''),
(105, 71, 'Edificio_prueba2', 0, 'extraordinaria', 6, 'Marzo', '2017', 15, 6, 2018, '3:00 AM', 'sdsds', '1. sss<br>;2. dsdsfffsf<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(106, 84, 'Residencial Refa X', 1, 'extraordinaria', 4, 'Julio', '2018', 19, 6, 2018, '7:00 PM', 'Parqueo del residencial', '1. Resumen de Gestion Financiera<br>;2. Temas libres<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(107, 20, 'Torre Carmil V', 0, 'ordinaria', 28, 'Junio', '2018', 19, 6, 2018, '7:00 PM', 'Area social', '1. Resumen de Gestion Financiera<br>;2. Temas libres<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(108, 107, 'Residencial Las Palmeras', 2, 'extraordinaria', 8, 'Julio', '2018', 20, 6, 2018, '3:00 PM', 'Gazebo', '1. Reestructuracion de la directiva<br>;2. Regulacion de la entrada a la cancha<br>;3. Trabajo de la seguridad<br>;4. Temas libres<br>;;;;;;;;;;;;;;;;', '', '', '', ''),
(109, 101, 'Torre Mario Augusto V', 1, 'extraordinaria', 10, 'Julio', '2018', 21, 6, 2018, '7:00 PM', 'Estacionamiento de la torre ', '1. Cierre 2017<br>;2. 1er semestre 2018<br>;3. Cuentas por cobrar<br>;4. Requerimientos legales apertura cuenta<br>;5. Ajustes Salariales<br>;6. Pintura Edficio (definir color+ aportes)<br>;7. Gestion del edificio (uniformes y otros)<br>;8. Temas libres<br>;;;;;;;;;;;;', '', '', '', ''),
(110, 74, 'Torre Natali', 1, 'extraordinaria', 5, 'Julio', '2018', 25, 6, 2018, '7:00 PM', 'del parqueo', '1. Reorganización de los parqueos asignados a cada apartamento, de acuerdo al plano aprobado por el Ayuntamiento del Distrito Nacional.<br>;2. Elección de la directiva<br>;3.  Metas en proceso de gestión<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(111, 125, 'Altos De Alameda 2', 2, 'ordinaria', 7, 'Julio', '2018', 2, 7, 2018, '2:00 PM', 'Salon Multiuso', '1. Presupuesto del año del condominio Altos De Alameda 2<br>;2. Las metas del año<br>;3. Temas pendiente de aprobación en asamblea<br>;4. Reglamento del condominio<br>;5. Tema Libre<br>;;;;;;;;;;;;;;;', '', '', '', ''),
(112, 127, 'Residencial Mario Augusto I', 0, 'ordinaria', 26, 'Julio', '2018', 2, 7, 2018, '7:00 PM', 'Parqueo', '1. Presentación de la empresa de administración<br>;2. Presupuesto del año del condominio<br>;3. Propuestas de aumento de mantenimiento (si hace falta)<br>;4. Las metas del año<br>;5. Los temas pendiente de aprobación en asamblea<br>;;;;;;;;;;;;;;;', 'Cada Propietario llevara su Silla', '', '', ''),
(113, 122, 'Torre P-A-33', 2, 'ordinaria', 12, 'Julio', '2018', 4, 7, 2018, '7:00 PM', 'Area social', '1. Resumen de Gestion Financiera<br>;2. Confirmacion de la directiva de la torre <br>;3. Autorización apertura de cuentas corrientes a nombre del condominio Torre PA-33<br>;4. Revisión y aprobación presupuesto definitivo y proyectos año 2018<br>;5. Conocimiento temas de convivencia pendientes de solución<br>;6.  Temas libres<br>;;;;;;;;;;;;;;', '', '', '', ''),
(114, 71, 'Edificio_prueba2', 1, 'extraordinaria', 10, 'Diciembre', '2025', 20, 7, 2018, '4:00 PM', 'wewe', '1. sss<br>;;;;;;;;;;;;;;;;;;;', 'jkjhjhjhjh', '', '', ''),
(115, 127, 'Residencial Mario Augusto I', 1, 'ordinaria', 4, 'Agosto', '2018', 26, 7, 2018, '7:00 PM', 'Parqueo', '1. Presentacion de la empresa<br>;2. Presupuesto<br>;3. Metas Pendientes de realizar <br>;4. Temas Pendiente de aprobacion <br>;5. Tema Libre<br>;;;;;;;;;;;;;;;', '', '', '', ''),
(116, 105, 'Torre Neapolis II', 2, 'extraordinaria', 22, 'Agosto', '2018', 27, 7, 2018, '7:00 PM', 'Salon nivel 1', '1. Resumen financiero 1er semestre 2018<br>;2. Metas gestionadas y por gestionar<br>;3. Normas del condominio<br>;4. Gastos generales-presupuesto...<br>;;;;;;;;;;;;;;;;', '', '', '', ''),
(118, 71, 'Edificio_prueba2', 1, 'extraordinaria', 4, 'Abril', '2021', 9, 8, 2018, '2:00 AM', 'sdsds', '1. momom<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(117, 71, 'Edificio_prueba2', 1, 'extraordinaria', 14, 'Noviembre', '2028', 30, 7, 2018, '10:00 AM', 'dsdsdsd', '1. sss<br>;;;;;;;;;;;;;;;;;;;', 'kkkk', '', '', ''),
(119, 119, 'Residencial Tierra Alta', 0, 'extraordinaria', 9, 'Septiembre', '2018', 13, 8, 2018, '3:00 PM', 'Gazebo del residencial ', '1. Resumen Gestion Financiera<br>;2. Sentencia ProConsumidor <br>;3. Eleccion nueva directiva<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(120, 121, 'Residencial Altos De Alameda', 2, 'ordinaria', 15, 'Septiembre', '2018', 18, 8, 2018, '4:00 PM', 'Gazebo', '1. Cambio de Directiva<br>;2. Temas Libres<br>;;;;;;;;;;;;;;;;;;', '', 'minutas_subidas/Minuta-15-Septiembre-2018-Residencial Altos De Alameda.pdf', '', 'actas_presenciales_subidas/acta_presencial-15-Septiembre-2018-Residencial Altos De Alameda.pdf'),
(121, 47, 'Residencial Don Carlos IX', 1, 'ordinaria', 23, 'Septiembre', '2018', 19, 9, 2018, '7:00 PM', 'Apartamento A-103', '1. Estados Financieros 2017<br>;2. Continuación reparación parqueo soterrado.<br>;3. Aprobación de venta espacio debajo de las escaleras del parqueo soterrado.<br>;4. Revisión de reparaciones pendientes del condominio.<br>;;;;;;;;;;;;;;;;', '', '', '', ''),
(122, 128, 'Torre de Londres II', 0, 'ordinaria', 9, 'Octubre', '2018', 25, 9, 2018, '7:00 PM', 'Parqueo', '1. Presentacion Empresa <br>;2. Presupuesto <br>;3. Metas Pendientes de realizar<br>;4. Socialización de normas de convivencias para condóminos y normas de empleados<br>;5. Aprobación de Mantenimiento de planta<br>;6. Cuota extraordinario no pagadas<br>;7. Cuota Extraordinario para diciembre<br>;8. Establecimiento de mora por atraso<br>;9. Temas Libre<br>;;;;;;;;;;;', '', 'minutas_subidas/Minuta-9-Octubre-2018-Torre de Londres II.pdf', 'asambleas_subidas/asamblea_subida-9-Octubre-2018-Torre de Londres II.pdf', 'actas_presenciales_subidas/acta_presencial-9-Octubre-2018-Torre de Londres II.pdf'),
(123, 115, 'Terraza Al Jardin', 2, 'ordinaria', 3, 'Octubre', '2018', 26, 9, 2018, '7:00 PM', 'salon social de la torre', '1. Analisis Financiero<br>;2. Avances de  gestión <br>;3. Morosidad<br>;4. Cuota Extra para la pintura <br>;5. Selección de nuevos miembros de la directiva<br>;6. Temas libre<br>;;;;;;;;;;;;;;', '', '', '', ''),
(124, 119, 'Residencial Tierra Alta', 0, 'extraordinaria', 7, 'Octubre', '2018', 1, 10, 2018, '3:00 PM', 'Gazebo del residencial', '1. Resumen Gestión Financiera<br>;2.  Sentencia Pro Consumidor <br>;3. Elección nueva directiva<br>;;;;;;;;;;;;;;;;;', '', 'minutas_subidas/Minuta-7-Octubre-2018-Residencial Tierra Alta.pdf', '', 'actas_presenciales_subidas/acta_presencial-7-Octubre-2018-Residencial Tierra Alta.pdf'),
(125, 113, 'Residencial Garden City', 1, 'ordinaria', 21, 'Octubre', '2018', 2, 10, 2018, '4:00 PM', 'de la cancha', '1. Entrega de 2da etapa<br>;2. Presupuesto general incluyendo 2da etapa<br>;3. Gas comun 2da etapa<br>;4. Resumen financiero<br>;5. Definir elecciones nueva directiva<br>;6. Metas logradas y pendientes<br>;7. Tema libre<br>;;;;;;;;;;;;;', '', '', '', ''),
(126, 129, 'View Tower', 2, 'extraordinaria', 15, 'Octubre', '2018', 4, 10, 2018, '7:00 PM', 'Lobby de la torre ', '1. Trabajos contratados (seguridad y puerta de emergencia)<br>;2. Ruidos fuera de horario<br>;3. Cuentas por pagar <br>;4. Uso del sticker para la basura<br>;5. avance de tema de la CAASD<br>;6.  Propuestas para mejoras del condominio<br>;7. Presupuesto del condominio (En caso de que la cuota actual no sea suficiente)<br>;;;;;;;;;;;;;', '', 'minutas_subidas/Minuta-15-Octubre-2018-View Tower.pdf', 'asambleas_subidas/asamblea_subida-15-Octubre-2018-View Tower.pdf', 'actas_presenciales_subidas/acta_presencial-15-Octubre-2018-View Tower.pdf'),
(127, 71, 'Edificio_prueba2', 1, 'ordinaria', 14, 'Septiembre', '2029', 6, 10, 2018, '2:00 PM', 'sdsds', '1. momom<br>;;;;;;;;;;;;;;;;;;;', 'sdsds', '', '', ''),
(128, 71, 'Edificio_prueba2', 1, 'extraordinaria', 3, 'Febrero', '2016', 6, 10, 2018, '2:00 PM', 'sdsds', '1. sss<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(129, 71, 'Edificio_prueba2', 1, 'extraordinaria', 2, 'Marzo', '2016', 6, 10, 2018, '2:00 AM', 'wewe', '1. sss<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(130, 71, 'Edificio_prueba2', 1, 'extraordinaria', 2, 'Marzo', '2016', 6, 10, 2018, '2:00 AM', 'wewe', '1. sss<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(131, 71, 'Edificio_prueba2', 1, 'ordinaria', 1, 'Enero', '2017', 11, 10, 2018, '1:00 AM', 'www', '1. momom<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(132, 71, 'Edificio_prueba2', 1, 'extraordinaria', 3, 'Febrero', '2016', 11, 10, 2018, '2:00 AM', 'sdsdd', '1. sss<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(133, 131, 'Torre Martinez Burgos IV', 2, 'ordinaria', 31, 'Octubre', '2018', 16, 10, 2018, '7:00 PM', 'salon de la Torre', '1. Presentación de la empresa de administración<br>;2. Presupuesto del condominio<br>;3. Breve tutorial de uso del sistema<br>;4. Las metas del año<br>;5. Los temas pendiente de aprobacion en asamblea<br>;6. Temas libre<br>;;;;;;;;;;;;;;', '', 'minutas_subidas/Minuta-31-Octubre-2018-Torre Martinez Burgos IV.pdf', 'asambleas_subidas/asamblea_subida-31-Octubre-2018-Torre Martinez Burgos IV.pdf', 'actas_presenciales_subidas/acta_presencial-31-Octubre-2018-Torre Martinez Burgos IV.pdf'),
(134, 113, 'Residencial Garden City', 2, 'extraordinaria', 24, 'Noviembre', '2018', 26, 10, 2018, '4:00 PM', 'Parqueo frente al edificio 15', '1. Elecciones junta directiva<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(135, 121, 'Residencial Altos De Alameda', 2, 'extraordinaria', 24, 'Noviembre', '2018', 30, 10, 2018, '3:00 PM', 'Salon Multiuso', '1. Normas y uso del multiuso.<br>;;;;;;;;;;;;;;;;;;;', '', 'minutas_subidas/Minuta-24-Noviembre-2018-Residencial Altos De Alameda.pdf', '', 'actas_presenciales_subidas/acta_presencial-24-Noviembre-2018-Residencial Altos De Alameda.pdf'),
(136, 125, 'Altos De Alameda 2', 2, 'extraordinaria', 24, 'Noviembre', '2018', 30, 10, 2018, '3:00 PM', 'Salón Multiuso', '1. Normas y uso del multiuso <br>;;;;;;;;;;;;;;;;;;;', '', '', '', 'actas_presenciales_subidas/acta_presencial-24-Noviembre-2018-Altos De Alameda 2.pdf'),
(137, 92, 'Residencial Gisela I', 1, 'extraordinaria', 19, 'Noviembre', '2018', 15, 11, 2018, '7:00 PM', 'Parqueo', '1. Cuota extraordinaria para fin de año<br>;2. Tema de terraza<br>;3. Temas libres<br>;;;;;;;;;;;;;;;;;', 'Es de suma importancia su asistencia, ya que en esta asamblea se tomaran decisiones monetarias.', 'minutas_subidas/Minuta-19-Noviembre-2018-Residencial Gisela I.pdf', '', 'actas_presenciales_subidas/acta_presencial-19-Noviembre-2018-Residencial Gisela I.pdf'),
(138, 52, 'Condominio Summa I', 2, 'extraordinaria', 23, 'Enero', '2019', 27, 11, 2018, '7:00 PM', 'salon de la Torre', '1. Pagos <br>;2. Mora<br>;3. Presentación Estados financieros <br>;4. Directiva<br>;5. Tema Libre<br>;;;;;;;;;;;;;;;', '', '', '', ''),
(139, 86, 'Gardenias I', 0, 'ordinaria', 14, 'Enero', '2019', 29, 11, 2018, '7:00 PM', 'Parqueo', '1. Selección de Nueva Directiva<br>;2. Temas Libres<br>;;;;;;;;;;;;;;;;;;', 'Le pedimos hagan llegar sus planchas conformadas para ser tomadas en cuentas.', '', '', ''),
(140, 127, 'Residencial Mario Augusto I', 1, 'extraordinaria', 29, 'Enero', '2019', 3, 1, 2019, '7:00 PM', 'Area de parqueo', '1. Salud Financiera del condominio / Reajuste de presupuesto<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(141, 113, 'Residencial Garden City', 2, 'extraordinaria', 27, 'Enero', '2019', 9, 1, 2019, '4:00 PM', 'Parqueo frente al edificio 15', '1. Presupuesto<br>;2. Ubicacion de medidores de gas en la etapa 2<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(142, 105, 'Torre Neapolis II', 2, 'ordinaria', 7, 'Febrero', '2019', 13, 1, 2019, '7:00 PM', 'Salón del nivel 1', '1. Situación financiera del condominio - Reajuste <br>;2. Revisión de normas de convivencia <br>;3. Avances y pendientes por lograr... <br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(143, 129, 'View Tower', 2, 'extraordinaria', 22, 'Enero', '2019', 14, 1, 2019, '7:00 PM', 'Lobby de la torre ', '1. Eleccion de Consejo de administracion <br>;2. Temas libres<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(144, 20, 'Torre Carmil V', 2, 'extraordinaria', 7, 'Febrero', '2019', 22, 1, 2019, '6:00 PM', 'Area social', '1. Informe financiero y presupuesto del condominio<br>;2. Metas pendientes del condominio<br>;;;;;;;;;;;;;;;;;;', 'En caso de no haber el 50% + 1, hayan pasado las 2 horas automaticamente se abrira una segunda convocatoria en donde solo bastara el 33% de los propietarios para que sea valida.\r\n\r\nApoyandonos en la Ley 122-05 de Regulación y Fomento de  las  Asociaciones  Sin Fines  de Lucro', '', '', ''),
(145, 19, 'Torre NE', 2, 'extraordinaria', 16, 'Febrero', '2019', 31, 1, 2019, '2:00 PM', 'de parqueo', '1. Resumen financiero 2018<br>;2. Instacion de camaras de seguridad<br>;3. Temas libres<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(146, 113, 'Residencial Garden City', 1, 'extraordinaria', 10, 'Febrero', '2019', 4, 2, 2019, '4:00 PM', 'Parqueo frente al edificio 15', '1. Presupuesto y cuota de mantenimiento<br>;2. Tema libre<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(147, 119, 'Residencial Tierra Alta', 0, 'extraordinaria', 24, 'Febrero', '2019', 5, 2, 2019, '3:00 PM', 'Gazebo del Residencial', '1. Información financiera del Residencial<br>;2. Temas libres<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(148, 69, 'Torre P-A-37', 1, 'extraordinaria', 26, 'Febrero', '2019', 8, 2, 2019, '7:00 PM', 'Del parqueo', '1. Resumen financiero 2018<br>;2. Presupuesto del condominio<br>;3. Metas pendientes por hacer<br>;4. Cumplimiento de las normas del condominio<br>;;;;;;;;;;;;;;;;', '', '', '', ''),
(149, 71, 'Edificio_prueba2', 1, 'extraordinaria', 3, 'Febrero', '2016', 12, 2, 2019, '2:00 AM', 'Gazebo', '1. prueba<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(150, 118, 'Torre Teraluz II', 1, 'ordinaria', 13, 'Marzo', '2019', 28, 2, 2019, '7:00 PM', 'social', '1. Resumen financiero del año<br>;2. Presupuesto del año<br>;3. Metas logradas del año y pendientes para el proximo<br>;4. Cambio/confirmacion de la directiva<br>;5. Propuesta de cuota extra para fondo de la futura pintura del condominio<br>;;;;;;;;;;;;;;;', '', '', '', ''),
(151, 128, 'Torre de Londres II', 1, 'extraordinaria', 12, 'Marzo', '2019', 2, 3, 2019, '7:00 PM', 'Parqueo de la torre', '1. Conocer situación financiera y ajuste de nomina<br>;2. Evaluar, revisar y decidir los proyectos y remo-delaciones de la torre<br>;3. Elecciones de nueva directiva <br>;4. Temas abiertos <br>;;;;;;;;;;;;;;;;', '', '', '', ''),
(152, 107, 'Residencial Las Palmeras', 2, 'extraordinaria', 10, 'Marzo', '2019', 4, 3, 2019, '3:00 PM', '2do gazebo ', '1. Informe financiero (asenfi)<br>;2. Lisitacion de varias administraciones <br>;3. Temas libres <br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(153, 133, 'Altos de alameda 3', 2, 'extraordinaria', 23, 'Marzo', '2019', 8, 3, 2019, '10:00 AM', 'Salon Multiuso', '1. Entrega formal del condominio <br>;2.  Aporte cuota del mantenimiento <br>;3. Selección de la directiva<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(154, 122, 'Torre P-A-33', 2, 'ordinaria', 11, 'Abril', '2019', 28, 3, 2019, '7:00 PM', 'social', '1. Resumen financiero del año<br>;2. Objetivos logrados y objetivos pendientes<br>;3. Aumento de la basura y revision del presupuesto<br>;4. Nueva cuenta del condominio<br>;5. Confirmacion/cambio de la directiva<br>;6. Propuesta de Rack de botellones de agua<br>;7. Temas libres<br>;;;;;;;;;;;;;', '', '', '', ''),
(155, 121, 'Residencial Altos De Alameda', 2, 'extraordinaria', 13, 'Abril', '2019', 1, 4, 2019, '2:00 PM', 'Salon de actividades (multiuso)', '1. Presupuesto<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(156, 125, 'Altos De Alameda 2', 2, 'extraordinaria', 13, 'Abril', '2019', 1, 4, 2019, '2:00 PM', 'Salón de actividades  (Multiuso)', '1. Presupuesto<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(157, 107, 'Residencial Las Palmeras', 2, 'extraordinaria', 7, 'Abril', '2019', 4, 4, 2019, '4:00 PM', '2do gazebo ', '1. Presentación y Juramentacion (Nuevo consejo directivo) <br>;2. Presentación Progescon S.R.L (Empresa Administradora seleccionada comitiva)<br>;3. presentación Firmas Autorización apertura (Cuenta bancaria A Nombre del residencial ) <br>;;;;;;;;;;;;;;;;;', '-Llegar a tiempo a las citas y reuniones es una fase de auto disciplina y evidencia de respeto a si mismo. La puntualidad es un cumplido que la persona cortés paga a sus asociados como muestra de respecto. Dios les Bendiga. ', '', '', ''),
(158, 120, 'Condominio Luvi II', 1, 'ordinaria', 12, 'Abril', '2019', 12, 4, 2019, '8:00 PM', 'Parqueo de la torre', '1. Resumen financieros. <br>;2. Metas logradas y por lograr. <br>;3. Presupuesto de la torre. <br>;4. Propuesta pintura del edificio. <br>;5. Elecciones. <br>;6. Temas abiertos<br>;;;;;;;;;;;;;;', '', '', '', ''),
(159, 20, 'Torre Carmil V', 2, 'ordinaria', 8, 'Mayo', '2019', 25, 4, 2019, '6:00 PM', 'social', '1. Resumen financiero del condominio en el año<br>;2. Objetivos obtenidos y no obtenidos en el año<br>;3. Normativas y penalidades para los propietarios<br>;4. Eleccion nueva directiva periodo 2019/2020<br>;5. Temas libres<br>;;;;;;;;;;;;;;;', 'En caso de no haber el 50% + 1, hayan pasado las 2 horas automaticamente se abrira una segunda convocatoria en donde solo bastara el 33% de los propietarios para que sea valida. Apoyandonos en la Ley 122-05 de Regulación y Fomento de las Asociaciones Sin Fines de Lucro. .', '', '', ''),
(160, 135, 'M-45', 2, 'ordinaria', 15, 'Mayo', '2019', 27, 4, 2019, '7:00 PM', 'Area Social ', '1. Presentación de la empresa. <br>;2. Breve tutorial del uso del portal.<br>;3. Modificación de los estatutos.<br>;4. Presentación del presupuesto del año.<br>;5. Objetivos del año.<br>;6. Propuesta de colocación de medidores para el gas.<br>;7. Confirmación de la directiva y cambio de firma de la cuenta.<br>;8. Temas libres.<br>;;;;;;;;;;;;', '', '', '', ''),
(161, 103, 'Ciudad Bonita', 2, 'extraordinaria', 5, 'Mayo', '2019', 1, 5, 2019, '4:00 PM', 'Gazebo #1', '1. Ratificar a la Plancha Ganadora en las Elecciones 2019<br>;2. Palabras de los Representantes Salientes <br>;3. Palabras de los Representantes Entrantes<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(162, 131, 'Torre Martinez Burgos IV', 2, 'extraordinaria', 7, 'Mayo', '2019', 1, 5, 2019, '7:00 PM', 'Area Social ', '1. Apartamento 10-02 venta.<br>;2. Proyectos realizados y proyectos en curso.<br>;3. Presupuesto.<br>;4. Planta y sistema eléctrico.<br>;5. Cuota extra para pago de prestaciones.<br>;6. Temas Libres.<br>;;;;;;;;;;;;;;', '', '', '', ''),
(163, 137, 'Torre Galan II', 2, 'ordinaria', 21, 'Mayo', '2019', 3, 5, 2019, '6:00 PM', 'Salon de reunion ', '1. Confirmación de la directiva<br>;2. Enviar a legal después de tres cuotas de mantenimiento <br>;3. Inscripción de privilegio  <br>;4. Presentación de la nueva empresa de administración <br>;5. Normativa   alquiler por airbnb y afines<br>;6. Presentación presupuesto pintura de los parqueos, instalacion de camaras y mantenimiento a los portones y creacion de estructura en hierro. <br>;7. Temas Libres <br>;;;;;;;;;;;;;', '.', '', '', ''),
(164, 125, 'Altos De Alameda 2', 2, 'extraordinaria', 1, 'Junio', '2019', 8, 5, 2019, '2:00 PM', 'Salón Multiuso', '1. PRESUPUESTO<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(165, 121, 'Residencial Altos De Alameda', 2, 'extraordinaria', 1, 'Junio', '2019', 9, 5, 2019, '2:00 PM', 'Salon de actividades (multiuso)', '1. Presupuesto<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(166, 20, 'Torre Carmil V', 0, 'extraordinaria', 16, 'Mayo', '2019', 10, 5, 2019, '7:00 PM', 'del parqueo', '1. Eleccion de la directiva<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(167, 132, 'Nuevas Terrazas III', 1, 'ordinaria', 15, 'Junio', '2019', 13, 5, 2019, '4:00 PM', 'Parqueo del condominio Nuevas terrazas III ', '1. Propuestas de seguridad <br>;2. Potabilizacion del agua<br>;3. Modificación del articulo 9 que trata sobre el corum<br>;4. Revisar los articulos 12,25,39,44 y 48 del los estatutos<br>;5. Empleado nocturno<br>;6. Elecciones<br>;7. Presupuesto mayo-diciembre y balance de la cuenta a la fecha por parte de Asenfi <br>;;;;;;;;;;;;;', '\"Por favor traer su cédula o copia/foto del acto de venta', '', '', ''),
(168, 141, 'Torre San Pio X', 2, 'ordinaria', 13, 'Junio', '2019', 29, 5, 2019, '7:00 PM', 'Area de parqueo', '1. Presentación de la nueva Administración<br>;2. Elección de una Junta Directiva<br>;3. Presupuesto del año<br>;4. Metas del año<br>;5. Temas libres<br>;;;;;;;;;;;;;;;', '', '', '', ''),
(169, 51, 'Residencial Soler III', 1, 'ordinaria', 13, 'Junio', '2019', 4, 6, 2019, '7:00 PM', 'En el parqueo', '1. Informe financiero<br>;2. Fecha pago cuota del mantenimiento<br>;3. Elección y confirmación del consejo directivo<br>;4. Temas libres<br>;;;;;;;;;;;;;;;;', '', '', '', ''),
(170, 137, 'Torre Galan II', 1, 'extraordinaria', 21, 'Junio', '2019', 4, 6, 2019, '6:00 PM', 'Salon de reunion ', '1. Presentación  presupuesto de la torre<br>;2. Presentación presupuesto instalacion camaras, pintura y mantenimiento de los pontones y parqueos <br>;3. Temas libres<br>;;;;;;;;;;;;;;;;;', '.', '', '', ''),
(171, 149, 'Gil Roma XVII', 0, 'extraordinaria', 12, 'Junio', '2019', 6, 6, 2019, '7:00 PM', 'Área Social ', '1. Presentación de la Empresa <br>;2. Presupuesto<br>;3. Proyectos Futuros<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(172, 92, 'Residencial Gisela I', 1, 'ordinaria', 27, 'Junio', '2019', 7, 6, 2019, '7:00 PM', 'Area de parqueo', '1. Eleccion de una Junta Directiva<br>;2. Presupuesto del año<br>;3. Metas por realizar<br>;4. Propuesta sobre adquisición de la azotea del lado A del edificio<br>;;;;;;;;;;;;;;;;', 'Estimado propietario,\r\nPor medio de la presente le invitamos a la Asamblea Ordinaria del condominio a celebrarse el jueves 27 de junio a las 7pm en el área del parqueo.\r\nEn la misma trataremos los siguientes temas:\r\n-Elección de una Junta Directiva\r\n-Presupuesto del año\r\n-Metas por realizar\r\n-Propuesta sobre adquisición de la azotea del lado A del edificio\r\n\r\nSu presencia es de suma importancia para todo lo concerniente al condominio.\r\nLe esperamos.\r\n', '', '', ''),
(173, 103, 'Ciudad Bonita', 2, 'extraordinaria', 16, 'Junio', '2019', 10, 6, 2019, '4:00 PM', 'Gazebo #1', '1. Presentación del Plan de Trabajo de la Directiva 2019<br>;2. Reubicación de la oficina administrativa.<br>;3. Punto libre.<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(174, 53, 'Residencial Karen Pilar', 1, 'extraordinaria', 3, 'Julio', '2019', 21, 6, 2019, '7:00 PM', 'Área de reunión Residencial Karen Pilar', '1. Inscripción de privilegio apartamentos con deuda<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(175, 125, 'Altos De Alameda 2', 2, 'ordinaria', 25, 'Julio', '2019', 15, 7, 2019, '6:00 PM', 'Salón de actividades  (Multiuso)', '1. ELECCION DE NUEVA JUNTA DIRECTIVA<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(176, 125, 'Altos De Alameda 2', 2, 'ordinaria', 25, 'Julio', '2019', 15, 7, 2019, '6:00 PM', 'Salón de actividades  (Multiuso)', '1. ELECCION DE NUEVA JUNTA DIRECTIVA<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(177, 154, 'Torre Monaco II', 0, 'extraordinaria', 21, 'Agosto', '2019', 21, 8, 2019, '7:30 PM', 'Area social piso 10', '1. Presentacion de la nueva administracion<br>;2. Manejo de sistema de agua<br>;3. Preguntas/Conclusion<br>;;;;;;;;;;;;;;;;;', 'La participacion de todos es de suma importancia para lograr una gestion efectiva.\r\nLes esperamos', '', '', ''),
(223, 71, 'Edificio_prueba2', 1, 'extraordinaria', 29, 'Noviembre', '2019', 27, 11, 2019, '1:30 AM', 'Parqueo lote 10 AB', '1. prueba<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(179, 52, 'Condominio Summa I', 2, 'extraordinaria', 10, 'Septiembre', '2019', 26, 8, 2019, '7:00 PM', 'Salon de reunion ', '1. Presentación Estados Financieros <br>;2. Presentacion presupuesto de la torre <br>;3. Presentacion cotizacion compra ascensor <br>;4. Conformacion de la directiva <br>;5. Exoneracion 50% de la cuota del mantenimiento al presidente del consejo <br>;6. Temas libres <br>;;;;;;;;;;;;;;', '', '', '', ''),
(180, 52, 'Condominio Summa I', 2, 'extraordinaria', 25, 'Septiembre', '2019', 26, 8, 2019, '7:00 PM', 'Salon de reunion ', '1. Presentación Estados Financieros <br>;2. Presentacion presupuesto de la torre <br>;3. Presentacion cotizacion compra ascensor <br>;4. Conformacion de la directiva <br>;5. Exoneracion 50% de la cuota del mantenimiento al presidente del consejo <br>;6. Temas libres <br>;;;;;;;;;;;;;;', '', '', '', ''),
(181, 142, 'RESIDENCIAL WALDY 4', 2, 'ordinaria', 31, 'Agosto', '2019', 26, 8, 2019, '4:00 PM', 'Parqueo residencial', '1. PRESENTACION DE LA EMPRESA DE ADMINISTRACION<br>;2. BREVE TUTORIAL SOBRE USO DEL SISTEMA<br>;3. PRESPUESTO DEL AÑO<br>;4. METAS REALIZADAS Y PENDIENTES DEL AÑO<br>;5. REGLAMENTOS DEL RESIDENCIAL<br>;6. PROPUESTA CUOTA EXTRA<br>;7. PREGUNTAS Y RESPUESTAS<br>;;;;;;;;;;;;;', 'Los propietarios deberán asistir con su cedula de identidad y electoral, los inquilinos o apoderados con copia de cedula del propietario y un poder firmado por el propietario del inmueble, los nuevos propietarios con un acto de venta que valide su compra.', '', '', '');
INSERT INTO `asambleas` (`Codigo`, `Codigo_edificio`, `nombre_edificio`, `silla`, `tipo`, `dia`, `mes`, `ano`, `dia_digitada`, `mes_digitada`, `ano_digitada`, `hora`, `lugar_encuentro`, `situaciones`, `nota`, `imagen_minuta`, `imagen_asamblea`, `imagen_acta_presencial`) VALUES
(182, 122, 'Torre P-A-33', 2, 'extraordinaria', 4, 'Septiembre', '2019', 27, 8, 2019, '7:00 PM', 'Área social ', '1. Camaras de seguridad areas comunes instaladas por los residentes <br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(183, 122, 'Torre P-A-33', 2, 'extraordinaria', 4, 'Septiembre', '2019', 27, 8, 2019, '7:00 PM', 'Área social ', '1. Camaras de seguridad areas comunes instaladas por los residentes <br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(184, 71, 'Edificio_prueba2', 1, 'extraordinaria', 1, 'Marzo', '2018', 28, 8, 2019, '1:30 AM', 'del parqueo', '1. sdsd<br>;2. sdsd<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(185, 71, 'Edificio_prueba2', 1, 'extraordinaria', 16, 'Agosto', '2027', 28, 8, 2019, '9:00 AM', 'sdsdsds', '1. sdsd<br>;2. sdsd<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(186, 71, 'Edificio_prueba2', 1, 'extraordinaria', 17, 'Agosto', '2029', 28, 8, 2019, '7:30 AM', 'sdsds', '1. aaaaaaaaa<br>;2. dddddd<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(187, 71, 'Edificio_prueba2', 1, 'extraordinaria', 13, 'Octubre', '2026', 28, 8, 2019, '8:00 AM', 'sdsds', '1. sdsdd<br>;2. sdsdsd<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(188, 71, 'Edificio_prueba2', 1, 'extraordinaria', 13, 'Octubre', '2026', 28, 8, 2019, '8:00 AM', 'sdsds', '1. sdsdd<br>;2. sdsdsd<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(189, 113, 'Residencial Garden City', 2, 'extraordinaria', 15, 'Septiembre', '2019', 3, 9, 2019, '3:00 PM', 'Parqueo frente al edificio 15', '1. Entrega de etapa 3<br>;2. Presentacion de presupuesto y cuota de mantenimiento<br>;3. Temas libres<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(190, 113, 'Residencial Garden City', 2, 'extraordinaria', 15, 'Septiembre', '2019', 3, 9, 2019, '3:00 PM', 'Parqueo frente al edificio 15', '1. Entrega de etapa 3<br>;2. Presentacion de presupuesto y cuota de mantenimiento<br>;3. Temas libres<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(191, 150, 'Madelainne 2', 2, 'ordinaria', 14, 'Septiembre', '2019', 8, 9, 2019, '4:00 PM', 'Gazebo', '1. PRESENTACION DE LA EMPRESA DE ADMINISTRACION<br>;2. BREVE TUTORIAL SOBRE USO DEL SISTEMA<br>;3. ESCOGER NUEVAS AUTORIDADES DEL RESIDENCIAL<br>;4. CUOTAS MANTENIMIENTO EN ATRASO<br>;5. PRESPUESTO DEL AÑO<br>;6. METAS REALIZADAS Y PENDIENTES DEL AÑO<br>;7. PREGUNTAS Y RESPUESTAS<br>;;;;;;;;;;;;;', '', '', '', ''),
(192, 105, 'Torre Neapolis II', 1, 'extraordinaria', 12, 'Septiembre', '2019', 12, 9, 2019, '7:00 PM', 'Salón del nivel 1', '1. Solución al problema de rebosamiento y daño del filtrante del condominio<br>;2. Gestiones realizadas<br>;3. Solucion definitiva emergente:  Costo del procedimiento / Cuota - Presupuesto<br>;;;;;;;;;;;;;;;;;', 'Favor llevar su silla.', '', '', ''),
(193, 105, 'Torre Neapolis II', 1, 'extraordinaria', 12, 'Septiembre', '2019', 12, 9, 2019, '7:00 PM', 'Salón del nivel 1', '1. Solución al problema de rebosamiento y daño del filtrante del condominio<br>;2. Gestiones realizadas<br>;3. Solucion definitiva emergente:  Costo del procedimiento / Cuota - Presupuesto<br>;;;;;;;;;;;;;;;;;', 'Favor llevar su silla.', '', '', ''),
(194, 152, 'Residencial Portofino', 1, 'extraordinaria', 12, 'Septiembre', '2019', 12, 9, 2019, '7:30 PM', 'Parqueo', '1. Presentación de la empresa administradora.<br>;2. Empleados del residencial.<br>;3. Situación deuda con el ayuntamiento. <br>;4. Situación actual Planta Eléctrica.<br>;5. Situación actual bomba de agua. <br>;6. Situación general infraestructura del edificio<br>;7. Presupuesto propuesto.<br>;8. Cuentas por cobrar y cuentas por pagar.<br>;9. Apertura de cuenta a nombre del residencial. <br>;10. Autorización inscripción de privilegios.<br>;11. Proyecto anual.<br>;12. Temas libres<br>;;;;;;;;', '', '', '', ''),
(195, 152, 'Residencial Portofino', 1, 'extraordinaria', 12, 'Septiembre', '2019', 12, 9, 2019, '7:30 PM', 'Parqueo', '1. Presentación de la empresa administradora.<br>;2. Empleados del residencial.<br>;3. Situación deuda con el ayuntamiento. <br>;4. Situación actual Planta Eléctrica.<br>;5. Situación actual bomba de agua. <br>;6. Situación general infraestructura del edificio<br>;7. Presupuesto propuesto.<br>;8. Cuentas por cobrar y cuentas por pagar.<br>;9. Apertura de cuenta a nombre del residencial. <br>;10. Autorización inscripción de privilegios.<br>;11. Proyecto anual.<br>;12. Temas libres<br>;;;;;;;;', '', '', '', ''),
(196, 132, 'Nuevas Terrazas III', 1, 'extraordinaria', 3, 'Octubre', '2019', 14, 9, 2019, '7:00 PM', 'Parqueo del edificio AL', '1. Elecciones<br>;;;;;;;;;;;;;;;;;;;', 'Recordar que las elecciones inician a las 7 pm y cerraran a las 9 pm ', '', '', ''),
(197, 132, 'Nuevas Terrazas III', 1, 'ordinaria', 3, 'Octubre', '2019', 14, 9, 2019, '7:00 PM', 'Parqueo del edificio AL nuevas terrazas III.', '1. Elecciones<br>;;;;;;;;;;;;;;;;;;;', 'Las elecciones iniciaran a las 7 pm y se cerraran a las 9 pm', '', '', ''),
(198, 148, 'Liam Sarasota', 0, 'extraordinaria', 30, 'Octubre', '2019', 23, 10, 2019, '7:00 PM', 'Área de reunión Residencial ', '1. Presentación de trabajos de acondicionamientos<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(199, 113, 'Residencial Garden City', 1, 'extraordinaria', 23, 'Noviembre', '2019', 5, 11, 2019, '4:00 PM', 'Parqueo frente al edificio 9', '1. Ubicacion de la Oficina administrativa<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(200, 113, 'Residencial Garden City', 1, 'extraordinaria', 23, 'Noviembre', '2019', 5, 11, 2019, '4:00 PM', 'Parqueo frente al edificio 9', '1. Ubicacion de la Oficina administrativa<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(201, 113, 'Residencial Garden City', 1, 'extraordinaria', 23, 'Noviembre', '2019', 5, 11, 2019, '4:00 PM', 'Parqueo frente al edificio 9', '1. Ubicacion de la Oficina administrativa<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(202, 113, 'Residencial Garden City', 1, 'extraordinaria', 23, 'Noviembre', '2019', 5, 11, 2019, '4:00 PM', 'Parqueos ubicados frente al edificio 9', '1. Ubicacion de la Oficina administrativa<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(203, 113, 'Residencial Garden City', 1, 'extraordinaria', 23, 'Noviembre', '2019', 5, 11, 2019, '4:00 PM', 'Parqueos ubicados frente al edificio 9', '1. Ubicacion de la Oficina administrativa<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(204, 113, 'Residencial Garden City', 1, 'extraordinaria', 23, 'Noviembre', '2019', 5, 11, 2019, '4:00 PM', 'Parqueos ubicados frente al edificio 9', '1. Ubicacion de la Oficina administrativa<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(205, 72, 'edificio de prueba 3', 1, 'extraordinaria', 14, 'Noviembre', '2024', 5, 11, 2019, '9:00 AM', 'Parqueo lote 10 AB', '1. - Presupuesto del condominio (En caso de que la cuota actual no sea suficiente)<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(206, 89, 'Torre Galco VIII', 2, 'ordinaria', 12, 'Noviembre', '2019', 6, 11, 2019, '7:00 PM', 'Area social', '1. Presentación Estados Financieros <br>;2. Presentación presupuesto de la torre <br>;3. Confirmación de la directiva<br>;4. Temas libres<br>;;;;;;;;;;;;;;;;', '', '', '', ''),
(210, 168, 'Torre Arpel II', 1, 'extraordinaria', 3, 'Diciembre', '2019', 22, 11, 2019, '7:30 PM', 'Arpel Tower II ', '1. Presentacion de Administracion <br>;2. Eleccion de directiva <br>;3. Metas por orden de prioridad <br>;;;;;;;;;;;;;;;;;', 'Es sumamente importante su asistencia. ', '', '', ''),
(230, 136, 'Brisas de las Colinas ll Lote 10', 2, 'ordinaria', 14, 'Enero', '2020', 11, 1, 2020, '7:30 PM', 'Parqueo Edificio Lote 10 AB', '1. Copia diferentes contratos realizados<br>;2. Asuntos daños de vicios de construcción GHR<br>;3. Situación Bomba común<br>;4. Estado de cuentas por Cobrar Lote<br>;5. Situación Contenedor basura Lote 10 <br>;6. Tema Libre<br>;;;;;;;;;;;;;;', 'Se convoca por segunda vez asamblea ordinaria, ya que la asamblea convocada en fecha 11 de enero del 2020, no obtuvo la asistencia requerida para ejecutarse. \r\nContamos con la presenta de todos.\r\n\r\n', '', '', ''),
(229, 124, 'Regatta Unique', 1, 'extraordinaria', 5, 'Febrero', '2020', 7, 1, 2020, '7:00 PM', 'Area de la piscina', '1. Normas para uso areas sociales y comunes<br>;2. Temas libres<br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(228, 179, 'Condominio LP7', 2, 'extraordinaria', 25, 'Enero', '2020', 3, 1, 2020, '4:00 PM', 'Gazebo del Residencial', '1. Presentacion Asenfi<br>;2. Modificaciones al Manual de Convivencia<br>;3. Cuota Extra<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(227, 153, 'Pablo Mella Manzana L', 2, 'extraordinaria', 11, 'Enero', '2020', 26, 12, 2019, '3:00 PM', 'Gazebo de la Manzana L', '1. Eleccion Presidente Directiva Manzana L<br>;2. Aprobacion de sanciones y multas por faltas al reglamento <br>;3. Reglamento de la glorieta, horario de actividades y depositos <br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(226, 153, 'Pablo Mella Manzana L', 2, 'extraordinaria', 11, 'Enero', '2020', 26, 12, 2019, '3:00 PM', 'Gazebo de la Manzana L', '1. Eleccion Presidente Directiva Manzana L<br>;2. Aprobacion de sanciones y multas por faltas al reglamento <br>;3. Reglamento de la glorieta, horario de actividades y depositos <br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(216, 71, 'Edificio_prueba2', 1, 'extraordinaria', 6, 'Diciembre', '2019', 26, 11, 2019, '1:30 AM', 'prueba', '1. prueba<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(217, 154, 'Torre Monaco II', 1, 'extraordinaria', 9, 'Diciembre', '2019', 26, 11, 2019, '7:30 PM', 'Terraza del piso 10 ', '1. Información financiera <br>;2. Compartir navideño <br>;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(222, 71, 'Edificio_prueba2', 1, 'extraordinaria', 30, 'Noviembre', '2019', 27, 11, 2019, '2:00 AM', 'prueba', '1. prueba<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(220, 71, 'Edificio_prueba2', 1, 'extraordinaria', 30, 'Noviembre', '2019', 27, 11, 2019, '6:00 AM', 'prueba', '1. prueba<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(221, 71, 'Edificio_prueba2', 1, 'extraordinaria', 30, 'Noviembre', '2019', 27, 11, 2019, '6:00 AM', 'prueba', '1. prueba<br>;;;;;;;;;;;;;;;;;;;', '', '', '', ''),
(231, 122, 'Torre P-A-33', 2, 'extraordinaria', 22, 'Enero', '2020', 14, 1, 2020, '7:00 PM', 'Área social ', '1. Decoración del lobby <br>;2. Contemplar declaracion jurada en el presupuesto <br>;3. Gym cerrar con llave o dejar abierto <br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(232, 134, 'Residencial LP9', 0, 'extraordinaria', 1, 'Febrero', '2020', 17, 1, 2020, '9:00 AM', 'Parqueo edificio 30 y 31', '1. Presentación de empresas de administración.<br>;2. Evaluación de presupuesto.<br>;3. Votación y elección de empresa administradora. <br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(233, 134, 'Residencial LP9', 0, 'extraordinaria', 1, 'Febrero', '2020', 17, 1, 2020, '9:00 AM', 'Parqueo edificio 30 y 31', '1. Presentación de empresas de administración.<br>;2. Evaluación de presupuesto.<br>;3. Votación y elección de empresa administradora. <br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(234, 134, 'Residencial LP9', 0, 'extraordinaria', 1, 'Febrero', '2020', 17, 1, 2020, '9:00 AM', 'Parqueo edificio 30 y 31', '1. Presentación de empresas de administración.<br>;2. Evaluación de presupuesto.<br>;3. Votación y elección de empresa administradora. <br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(235, 134, 'Residencial LP9', 0, 'extraordinaria', 1, 'Febrero', '2020', 17, 1, 2020, '9:00 AM', 'Parqueo edificio 30 y 31', '1. Presentación de empresas de administración.<br>;2. Evaluación de presupuesto.<br>;3. Votación y elección de empresa administradora. <br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(236, 19, 'Torre NE', 2, 'ordinaria', 6, 'Febrero', '2020', 25, 1, 2020, '7:00 PM', 'Parqueo', '1. Resumen financiero del condominio en el año<br>;2. Presupuesto del año<br>;3. Metas del año: cámaras, intercom<br>;4. Inscripción de privilegios apto. Deudas<br>;5. Mudanza, cobrar RD$1,500 (Al entrar y al salir)<br>;6. Mora a los que pagan fuera de fecha <br>;7. Autorizacion por asamblea de nuevos propietarios (Depurar compradores)<br>;8. Realizar levantamiento para validación escape de gas todos los aptos. <br>;;;;;;;;;;;;', '', '', '', ''),
(242, 191, 'Residencial Margaret', 1, 'extraordinaria', 20, 'Febrero', '2020', 6, 2, 2020, '8:00 PM', 'Parqueo del condominio ', '1. Presentación de la nueva Administración <br>;2. Eleccion de directiva <br>;3. Evaluación de Gastos e Ingresos del condominio<br>;;;;;;;;;;;;;;;;;', 'Su presencia es sumamente importante para que juntos logremos los mejores resultados. ', '', '', ''),
(241, 191, 'Residencial Margaret', 1, 'extraordinaria', 20, 'Febrero', '2020', 6, 2, 2020, '8:00 PM', 'Parqueo del condominio ', '1. Presentación de la nueva Administración <br>;2. Eleccion de directiva <br>;3. Evaluación de Gastos e Ingresos del condominio<br>;;;;;;;;;;;;;;;;;', 'Su presencia es sumamente importante para que juntos logremos los mejores resultados. ', '', '', ''),
(240, 191, 'Residencial Margaret', 1, 'extraordinaria', 20, 'Febrero', '2020', 6, 2, 2020, '8:00 PM', 'Parqueo del condominio ', '1. Presentación de la nueva Administración <br>;2. Eleccion de directiva <br>;3. Evaluación de Gastos e Ingresos del condominio<br>;;;;;;;;;;;;;;;;;', 'Su presencia es sumamente importante para que juntos logremos los mejores resultados. ', '', '', ''),
(243, 147, 'Brisas de las Colinas ll Lote 9', 0, 'ordinaria', 8, 'Febrero', '2020', 7, 2, 2020, '7:30 PM', 'parqueos edificios AB y CD', '1. Compra de artículos vehículos mal estacionados.<br>;2. Colocar caja de seguridad llaves de paso de gas.<br>;3. Discutir rol de supervision de cada propietario<br>;;;;;;;;;;;;;;;;;', '', '', '', ''),
(244, 92, 'Residencial Gisela I', 1, 'extraordinaria', 13, 'Febrero', '2020', 10, 2, 2020, '7:30 AM', 'La Asamblea se llevara a cabo en el parqueo  ', '1. Eleccion de Nueva directiva <br>;2. presentación de Resúmenes Financieros <br>;3. Temas libres <br>;;;;;;;;;;;;;;;;;', 'Favor de llegar temprano a la Asamblea, es muy importante para nosotros contar con su presencia.', '', '', ''),
(245, 92, 'Residencial Gisela I', 1, 'extraordinaria', 13, 'Febrero', '2020', 10, 2, 2020, '7:30 AM', 'La Asamblea se llevara a cabo en el parqueo  ', '1. Eleccion de Nueva directiva <br>;2. presentación de Resúmenes Financieros <br>;3. Temas libres <br>;;;;;;;;;;;;;;;;;', 'Favor de llegar temprano a la Asamblea, es muy importante para nosotros contar con su presencia.', '', '', ''),
(246, 89, 'Torre Galco VIII', 2, 'extraordinaria', 12, 'Febrero', '2020', 10, 2, 2020, '7:00 AM', 'Área de parqueo', '1. Presentación Estados Financieros <br>;2. Presupuesto de la torre<br>;3. Confirmación de la directiva<br>;4. Presupuesto  sistema medidores de gas <br>;5. Temas libres <br>;;;;;;;;;;;;;;;', '.', '', '', ''),
(247, 136, 'Brisas de las Colinas ll Lote 10', 2, 'ordinaria', 23, 'Febrero', '2020', 10, 2, 2020, '4:00 PM', 'area verde, cancha de football', '1. Informe<br>;2. Aprobacion del Borrador del Manual de Convivencia<br>;3. Formalización de la Estructura de la Junta de Vecinos<br>;4. Escogencia de la Comisión Electoral<br>;;;;;;;;;;;;;;;;', 'Esta es una invitación a Asamblea General', '', '', ''),
(248, 175, 'Brisas de las colinas II (Lote 6)', 2, 'ordinaria', 23, 'Febrero', '2020', 10, 2, 2020, '4:00 PM', 'area verde, cancha de football', '1. Informe<br>;2. Aprobacion del Borrador del Manual de Convivencia<br>;3. Formalización de la Estructura de la Junta de Vecinos<br>;4. Escogencia de la Comisión Electoral<br>;;;;;;;;;;;;;;;;', 'Esta invitacion es para Asamblea General', '', '', ''),
(249, 190, 'Res. Laura Marina I', 1, 'ordinaria', 26, 'Febrero', '2020', 17, 2, 2020, '7:30 PM', 'Parqueo del condominio ', '1. Presentación de la nueva Administración <br>;2. Eleccion de directiva <br>;3. Evaluación de Gastos e Ingresos del condominio<br>;;;;;;;;;;;;;;;;;', 'Su presencia es de suma importancia para buenos resultados en la gestión. ', '', '', ''),
(250, 190, 'Res. Laura Marina I', 1, 'ordinaria', 26, 'Febrero', '2020', 17, 2, 2020, '7:30 PM', 'Parqueo del condominio ', '1. Presentación de la nueva Administración <br>;2. Eleccion de directiva <br>;3. Evaluación de Gastos e Ingresos del condominio<br>;;;;;;;;;;;;;;;;;', 'Su presencia es de suma importancia para buenos resultados en la gestión. ', '', '', ''),
(251, 190, 'Res. Laura Marina I', 1, 'ordinaria', 26, 'Febrero', '2020', 17, 2, 2020, '7:30 PM', 'Parqueo del condominio ', '1. Presentación de la nueva Administración <br>;2. Eleccion de directiva <br>;3. Evaluación de Gastos e Ingresos del condominio<br>;;;;;;;;;;;;;;;;;', 'Su presencia es de suma importancia para buenos resultados en la gestión. ', '', '', ''),
(252, 178, 'Torre Lilas Del Renacimiento', 0, 'extraordinaria', 12, 'Marzo', '2020', 24, 2, 2020, '7:30 PM', 'Salón multiuso ', '1. Presentación de la Administración <br>;2. Revisión del presupuesto <br>;3. Reajuste del mantenimiento <br>;4. Metas del condominio<br>;;;;;;;;;;;;;;;;', 'Su presencia es sumamente importante para lograr mejores resultados en el condominio. ', '', '', ''),
(253, 178, 'Torre Lilas Del Renacimiento', 0, 'extraordinaria', 12, 'Marzo', '2020', 24, 2, 2020, '7:30 PM', 'Salón multiuso ', '1. Presentación de la Administración <br>;2. Revisión del presupuesto <br>;3. Reajuste del mantenimiento <br>;4. Metas del condominio<br>;;;;;;;;;;;;;;;;', 'Su presencia es sumamente importante para lograr mejores resultados en el condominio. ', '', '', ''),
(254, 178, 'Torre Lilas Del Renacimiento', 0, 'extraordinaria', 12, 'Marzo', '2020', 24, 2, 2020, '7:30 PM', 'Salón multiuso ', '1. Presentación de la Administración <br>;2. Revisión del presupuesto <br>;3. Reajuste del mantenimiento <br>;4. Metas del condominio<br>;;;;;;;;;;;;;;;;', 'Su presencia es sumamente importante para lograr mejores resultados en el condominio. ', '', '', '');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `asambleas`
--
ALTER TABLE `asambleas`
  ADD PRIMARY KEY (`Codigo`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `asambleas`
--
ALTER TABLE `asambleas`
  MODIFY `Codigo` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=255;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
